// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/lockn/packages/backstage/internal/dao/internal"
)

// bsButtonPermissionsDao is the data access object for the table bs_button_permissions.
// You can define custom methods on it to extend its functionality as needed.
type bsButtonPermissionsDao struct {
	*internal.BsButtonPermissionsDao
}

var (
	// BsButtonPermissions is a globally accessible object for table bs_button_permissions operations.
	BsButtonPermissions = bsButtonPermissionsDao{internal.NewBsButtonPermissionsDao()}
)

// Add your custom methods and functionality below.
