// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/lockn/packages/backstage/internal/dao/internal"
)

// bsPermissionsDao is the data access object for the table bs_permissions.
// You can define custom methods on it to extend its functionality as needed.
type bsPermissionsDao struct {
	*internal.BsPermissionsDao
}

var (
	// BsPermissions is a globally accessible object for table bs_permissions operations.
	BsPermissions = bsPermissionsDao{internal.NewBsPermissionsDao()}
)

// Add your custom methods and functionality below.
