// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/lockn/packages/backstage/internal/dao/internal"
)

// bsRoutesDao is the data access object for the table bs_routes.
// You can define custom methods on it to extend its functionality as needed.
type bsRoutesDao struct {
	*internal.BsRoutesDao
}

var (
	// BsRoutes is a globally accessible object for table bs_routes operations.
	BsRoutes = bsRoutesDao{internal.NewBsRoutesDao()}
)

// Add your custom methods and functionality below.
