// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/lockn/packages/backstage/internal/dao/internal"
)

// bsRoleRoutesDao is the data access object for the table bs_role_routes.
// You can define custom methods on it to extend its functionality as needed.
type bsRoleRoutesDao struct {
	*internal.BsRoleRoutesDao
}

var (
	// BsRoleRoutes is a globally accessible object for table bs_role_routes operations.
	BsRoleRoutes = bsRoleRoutesDao{internal.NewBsRoleRoutesDao()}
)

// Add your custom methods and functionality below.
