// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/lockn/packages/backstage/internal/dao/internal"
)

// bsRolesDao is the data access object for the table bs_roles.
// You can define custom methods on it to extend its functionality as needed.
type bsRolesDao struct {
	*internal.BsRolesDao
}

var (
	// BsRoles is a globally accessible object for table bs_roles operations.
	BsRoles = bsRolesDao{internal.NewBsRolesDao()}
)

// Add your custom methods and functionality below.
