// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/lockn/packages/backstage/internal/dao/internal"
)

// bsUserRolesDao is the data access object for the table bs_user_roles.
// You can define custom methods on it to extend its functionality as needed.
type bsUserRolesDao struct {
	*internal.BsUserRolesDao
}

var (
	// BsUserRoles is a globally accessible object for table bs_user_roles operations.
	BsUserRoles = bsUserRolesDao{internal.NewBsUserRolesDao()}
)

// Add your custom methods and functionality below.
