// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"github.com/lockn/packages/backstage/api/auth"

	authLogic "github.com/lockn/packages/backstage/internal/logic/auth"
)

type ControllerV1 struct {
	auth *authLogic.Auth
}

func NewV1() auth.IAuthV1 {
	return &ControllerV1{auth: authLogic.New()}
}
